## Diving into the World of Deep Learning

Welcome to this exciting journey into the realm of Deep Learning! This notebook serves as your guide, offering a hands-on exploration of the core concepts and techniques that power this transformative field.

Deep Learning, a subset of Machine Learning, empowers computers to learn complex patterns and representations directly from data. Inspired by the structure and function of the human brain, Deep Learning models, also known as Artificial Neural Networks, have revolutionized areas such as image recognition, natural language processing, and robotics.

In this notebook, we'll embark on a practical adventure, starting with the fundamental building blocks of neural networks and progressing towards building and training your own models.  We'll unravel the magic behind backpropagation, the process that enables these networks to learn from data, and delve into techniques for optimizing model performance.

Get ready to witness the power of Deep Learning firsthand as we unlock the potential of data and embark on this thrilling learning experience together!

In [3]:
import numpy as np

# Create a 1D array
arr1 = np.array([1, 2, 3, 4, 5])
print("1D Array:\n", arr1)

# Create a 2D array
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print("\n2D Array:\n", arr2)

# Access elements
print("\nElement at index 2 of arr1:", arr1[2])
print("Element at row 1, column 2 of arr2:", arr2[1, 2])


# Array operations
arr3 = np.array([10, 20, 30, 40, 50]) # modified to match the length of arr1
print("\nSum of arr1 and arr3:", arr1 + arr3)  # element-wise addition
print("Product of arr1 and 2:", arr1 * 2) # element-wise multiplication

# Array attributes
print("\nShape of arr2:", arr2.shape)
print("Data type of arr1:", arr1.dtype)

# Array slicing
print("\nSliced arr1 from index 1 to 3:", arr1[1:4])
print("Sliced arr2, all rows, columns from 0 to 1:", arr2[:,0:2])

# Reshape an array
arr4 = np.arange(12)
print("\nOriginal array arr4:", arr4)
reshaped_arr4 = arr4.reshape(3, 4)
print("Reshaped array arr4:", reshaped_arr4)


# Basic statistics
print("\nMean of arr1:", np.mean(arr1))
print("Standard deviation of arr1:", np.std(arr1))

1D Array:
 [1 2 3 4 5]

2D Array:
 [[1 2 3]
 [4 5 6]]

Element at index 2 of arr1: 3
Element at row 1, column 2 of arr2: 6

Sum of arr1 and arr3: [11 22 33 44 55]
Product of arr1 and 2: [ 2  4  6  8 10]

Shape of arr2: (2, 3)
Data type of arr1: int64

Sliced arr1 from index 1 to 3: [2 3 4]
Sliced arr2, all rows, columns from 0 to 1: [[1 2]
 [4 5]]

Original array arr4: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped array arr4: [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Mean of arr1: 3.0
Standard deviation of arr1: 1.4142135623730951


Now let's see how we can visualize the array

In [6]:
import matplotlib.pyplot as plt

plot = plt.figure(figsize=(10, 5))



<Figure size 1000x500 with 0 Axes>

Let's play a bit with pandas

In [12]:
# prompt: Create some simple example with pandas. Create dataframe which documents 5 different species of animals. For each specie create few rows with different age of an animal - let's say it was the age of animal that was observed.

import pandas as pd

data = {'species': ['dog', 'dog', 'dog', 'cat', 'cat', 'cat', 'cat', 'bird', 'bird', 'bird', 'fish', 'fish', 'fish', 'snake', 'snake', 'snake'],
        'age': [1, 2, 3, 1, 2, 3, 4, 0.5, 1, 1.5, 0.2, 0.4, 0.6, 2, 3, 4]}

df = pd.DataFrame(data)
df

species  age
0      dog  1.0
1      dog  2.0
2      dog  3.0
3      cat  1.0
4      cat  2.0
5      cat  3.0
6      cat  4.0
7     bird  0.5
8     bird  1.0
9     bird  1.5
10    fish  0.2
11    fish  0.4
12    fish  0.6
13   snake  2.0
14   snake  3.0
15   snake  4.0

from matplotlib import pyplot as plt
df['age'].plot(kind='hist', bins=20, title='age')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
df.groupby('species').size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
df['age'].plot(kind='line', figsize=(8, 4), title='age')
plt.gca().spines[['top', 'right']].set_visible(False)

<string>:5: FutureWarning: 

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `y` variable to `hue` and set `legend=False` for the same effect.



from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(df['species'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(df, x='age', y='species', inner='stick', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)